///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Dyno
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DynoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("832833ec-76fc-437a-ac13-2166a0a73879")]
    public partial class DynoRepository : RepoGenBaseFolder
    {
        static DynoRepository instance = new DynoRepository();
        DynoRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        DynoRepositoryFolders.DashboardFinanceAndOperationsAppFolder _dashboardfinanceandoperations;

        /// <summary>
        /// Gets the singleton class instance representing the DynoRepository element repository.
        /// </summary>
        [RepositoryFolder("832833ec-76fc-437a-ac13-2166a0a73879")]
        public static DynoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DynoRepository() 
            : base("DynoRepository", "/", null, 0, false, "832833ec-76fc-437a-ac13-2166a0a73879", ".\\RepositoryImages\\DynoRepository832833ec.rximgres")
        {
            _applicationundertest = new DynoRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _dashboardfinanceandoperations = new DynoRepositoryFolders.DashboardFinanceAndOperationsAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("832833ec-76fc-437a-ac13-2166a0a73879")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("727b9b35-ce08-4cb6-95d6-2f0f73092b00")]
        public virtual DynoRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The DashboardFinanceAndOperations folder.
        /// </summary>
        [RepositoryFolder("d0134e65-a647-4eb5-a587-ed8458f88c29")]
        public virtual DynoRepositoryFolders.DashboardFinanceAndOperationsAppFolder DashboardFinanceAndOperations
        {
            get { return _dashboardfinanceandoperations; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class DynoRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("727b9b35-ce08-4cb6-95d6-2f0f73092b00")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "727b9b35-ce08-4cb6-95d6-2f0f73092b00", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("727b9b35-ce08-4cb6-95d6-2f0f73092b00")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("727b9b35-ce08-4cb6-95d6-2f0f73092b00")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The DashboardFinanceAndOperationsAppFolder folder.
        /// </summary>
        [RepositoryFolder("d0134e65-a647-4eb5-a587-ed8458f88c29")]
        public partial class DashboardFinanceAndOperationsAppFolder : RepoGenBaseFolder
        {
            DynoRepositoryFolders.PrimaryConductorFolder _primaryconductor;
            RepoItemInfo _spantagwqInfo;
            RepoItemInfo _signoutlabelInfo;

            /// <summary>
            /// Creates a new DashboardFinanceAndOperations  folder.
            /// </summary>
            public DashboardFinanceAndOperationsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DashboardFinanceAndOperations", "/dom[@domain='faras.afras.sa']", parentFolder, 30000, null, false, "d0134e65-a647-4eb5-a587-ed8458f88c29", "")
            {
                _primaryconductor = new DynoRepositoryFolders.PrimaryConductorFolder(this);
                _spantagwqInfo = new RepoItemInfo(this, "SpanTagWQ", ".//button[#'UserBtn']/span[@innertext='WQ']", ".//button[#'UserBtn']/span[@innertext='WQ']", 30000, null, "16ef50d4-a742-43aa-9aeb-4ad28c04d318");
                _signoutlabelInfo = new RepoItemInfo(this, "SignOutLabel", ".//span[#'SignOut_label']", ".//span[#'SignOut_label']", 30000, null, "5cb6fc7d-3ce4-4945-8667-a30c4105b69c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d0134e65-a647-4eb5-a587-ed8458f88c29")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d0134e65-a647-4eb5-a587-ed8458f88c29")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SpanTagWQ item.
            /// </summary>
            [RepositoryItem("16ef50d4-a742-43aa-9aeb-4ad28c04d318")]
            public virtual Ranorex.SpanTag SpanTagWQ
            {
                get
                {
                    return _spantagwqInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagWQ item info.
            /// </summary>
            [RepositoryItemInfo("16ef50d4-a742-43aa-9aeb-4ad28c04d318")]
            public virtual RepoItemInfo SpanTagWQInfo
            {
                get
                {
                    return _spantagwqInfo;
                }
            }

            /// <summary>
            /// The SignOutLabel item.
            /// </summary>
            [RepositoryItem("5cb6fc7d-3ce4-4945-8667-a30c4105b69c")]
            public virtual Ranorex.SpanTag SignOutLabel
            {
                get
                {
                    return _signoutlabelInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SignOutLabel item info.
            /// </summary>
            [RepositoryItemInfo("5cb6fc7d-3ce4-4945-8667-a30c4105b69c")]
            public virtual RepoItemInfo SignOutLabelInfo
            {
                get
                {
                    return _signoutlabelInfo;
                }
            }

            /// <summary>
            /// The PrimaryConductor folder.
            /// </summary>
            [RepositoryFolder("c61c95b3-7c95-4743-8c3a-c2bdd939f342")]
            public virtual DynoRepositoryFolders.PrimaryConductorFolder PrimaryConductor
            {
                get { return _primaryconductor; }
            }
        }

        /// <summary>
        /// The PrimaryConductorFolder folder.
        /// </summary>
        [RepositoryFolder("c61c95b3-7c95-4743-8c3a-c2bdd939f342")]
        public partial class PrimaryConductorFolder : RepoGenBaseFolder
        {
            RepoItemInfo _autotileInfo;
            RepoItemInfo _emailInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _systemadministrationInfo;

            /// <summary>
            /// Creates a new PrimaryConductor  folder.
            /// </summary>
            public PrimaryConductorFolder(RepoGenBaseFolder parentFolder) :
                    base("PrimaryConductor", ".//div[#'PrimaryConductor']", parentFolder, 30000, null, false, "c61c95b3-7c95-4743-8c3a-c2bdd939f342", "")
            {
                _autotileInfo = new RepoItemInfo(this, "AutoTile", "form[2]/div[5]/div/div[2]/div[2]/div/div/div[2]/div", "form[2]/div[5]/div/div[2]/div[2]/div/div/div[2]/div", 30000, null, "b7173c58-0d33-41f3-bfcd-d9e94c5ad35a");
                _emailInfo = new RepoItemInfo(this, "Email", "form[3]/div[5]/div/div[2]/div[2]/div[1]/div[4]/div/div[2]/div/div/div/div[1]/div[2]/div/div[1]/div[2]/div/div[3]/div[3]//div[@innertext='Email']", ".//div[@innertext='Email']", 30000, null, "7c5208fd-9e71-40d6-b577-830d332d48ed");
                _textInfo = new RepoItemInfo(this, "Text", "form[3]/div[5]/div/div[2]/div[2]/div[1]/div[4]/div/div[2]/div/div/div/div[1]/div[3]/div/div/div[1]/div[2]/div/div[1]//input[@type='text']", ".//input[@value='M.AbdulQayyum']", 30000, null, "7a7c8e6d-569a-4961-afee-61bb14d59d65");
                _systemadministrationInfo = new RepoItemInfo(this, "SystemAdministration", "form[@action='javascript:void(0)']/div[4]/div/div[2]/div[2]/div[2]/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div[2]/?/?/span[@innertext='System administration']", ".//span[@innertext='System administration']", 30000, null, "d0a11512-5a1f-4c74-a7f5-6e25df58fb14");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c61c95b3-7c95-4743-8c3a-c2bdd939f342")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c61c95b3-7c95-4743-8c3a-c2bdd939f342")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AutoTile item.
            /// </summary>
            [RepositoryItem("b7173c58-0d33-41f3-bfcd-d9e94c5ad35a")]
            public virtual Ranorex.DivTag AutoTile
            {
                get
                {
                    return _autotileInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The AutoTile item info.
            /// </summary>
            [RepositoryItemInfo("b7173c58-0d33-41f3-bfcd-d9e94c5ad35a")]
            public virtual RepoItemInfo AutoTileInfo
            {
                get
                {
                    return _autotileInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("7c5208fd-9e71-40d6-b577-830d332d48ed")]
            public virtual Ranorex.DivTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("7c5208fd-9e71-40d6-b577-830d332d48ed")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("7a7c8e6d-569a-4961-afee-61bb14d59d65")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("7a7c8e6d-569a-4961-afee-61bb14d59d65")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The SystemAdministration item.
            /// </summary>
            [RepositoryItem("d0a11512-5a1f-4c74-a7f5-6e25df58fb14")]
            public virtual Ranorex.SpanTag SystemAdministration
            {
                get
                {
                    return _systemadministrationInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SystemAdministration item info.
            /// </summary>
            [RepositoryItemInfo("d0a11512-5a1f-4c74-a7f5-6e25df58fb14")]
            public virtual RepoItemInfo SystemAdministrationInfo
            {
                get
                {
                    return _systemadministrationInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
