///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Dyno
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("c59c51ef-8687-4936-b138-acb2849398e1", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DynoRepository repository.
        /// </summary>
        public static DynoRepository repo = DynoRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardFinanceAndOperations.PrimaryConductor.SystemAdministration' at 63;18.", repo.DashboardFinanceAndOperations.PrimaryConductor.SystemAdministrationInfo, new RecordItemIndex(0));
            repo.DashboardFinanceAndOperations.PrimaryConductor.SystemAdministration.Click("63;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardFinanceAndOperations.PrimaryConductor.AutoTile' at 89;75.", repo.DashboardFinanceAndOperations.PrimaryConductor.AutoTileInfo, new RecordItemIndex(1));
            repo.DashboardFinanceAndOperations.PrimaryConductor.AutoTile.Click("89;75");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardFinanceAndOperations.PrimaryConductor.Email' at 63;7.", repo.DashboardFinanceAndOperations.PrimaryConductor.EmailInfo, new RecordItemIndex(2));
            repo.DashboardFinanceAndOperations.PrimaryConductor.Email.Click("63;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'm.abdulqayyum{Return}' with focus on 'DashboardFinanceAndOperations'.", repo.DashboardFinanceAndOperations.SelfInfo, new RecordItemIndex(3));
            repo.DashboardFinanceAndOperations.Self.EnsureVisible();
            Keyboard.Press("m.abdulqayyum{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardFinanceAndOperations.PrimaryConductor.Text' at 25;17.", repo.DashboardFinanceAndOperations.PrimaryConductor.TextInfo, new RecordItemIndex(4));
            repo.DashboardFinanceAndOperations.PrimaryConductor.Text.Click("25;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardFinanceAndOperations.SpanTagWQ' at 8;20.", repo.DashboardFinanceAndOperations.SpanTagWQInfo, new RecordItemIndex(5));
            repo.DashboardFinanceAndOperations.SpanTagWQ.Click("8;20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DashboardFinanceAndOperations.SignOutLabel' at 39;8.", repo.DashboardFinanceAndOperations.SignOutLabelInfo, new RecordItemIndex(6));
            repo.DashboardFinanceAndOperations.SignOutLabel.Click("39;8");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
